에러핸들링, 인가 구현
wecode-bootcamp-korea/37-2nd-skyski-backend pull request #5
Opened 2022-10-07 05:10 UTC by zwundzwzig

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 에러 핸들링 및 인가 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 에러핸들링 구현
- catchAsync 구현해 controller layer에서 에러 핸들링 구현했습니다.
- class 사용해 custom 에러 핸들링 구현했습니다.
- 글로벌 에러 핸들링 및 app.js에서 404 에러 핸들링도 구현했습니다.

2. 인가 기능 구현
- jwt 활용해 인가 기능 구현
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- class를 사용해 에러 핸들링 구현함으로써 새로운 에러 핸들링 기능을 구현할 수 있습니다.

<br />

## :: 기타 질문 및 특이 사항
- 에러 핸들링 피드백 부탁드립니다!

2022-10-07 06:06 UTC, bigfanoftim requested changes

2022-10-07 06:06 UTC, bigfanoftim commented on src/middlewares/auth.js
> +  req.admin = userAdmin;
네이밍, 컨벤션 신경써주세요!
```suggestion
  req.userId = userId;
  req.userKakaoId = userKakaoId;
  req.userAdmin = userAdmin;
```

2022-10-07 06:06 UTC, bigfanoftim commented on .gitignore
> +/src/middlewares/multer.js
`multer.js`를 gitignore에 추가하신 이유가 있나요?

2022-10-07 08:20 UTC, zwundzwzig commented on .gitignore
> +/src/middlewares/multer.js
multer에 AWS 버킷 정보가 있어서 혹시나 해서 이그노어 했습니다!

2022-10-11 01:55 UTC, bigfanoftim commented on .gitignore
> +/src/middlewares/multer.js
그럼 AWS정보만 .env에 추가해서 관리하면 될 것 같아요! 실제로 main 브랜치에 multer.js가 없다면 배포시에 코드가 동작하지 않을테니 다시 추가해 주세요.

2022-10-11 04:13 UTC, zwundzwzig commented on .gitignore
> +/src/middlewares/multer.js
넵 반영했습니다!

2022-10-11 04:24 UTC, bigfanoftim requested changes

2022-10-11 04:24 UTC, bigfanoftim commented on src/middlewares/multer.js
> +});
multer에 관한 리뷰는 이후에 실제로 multer를 사용하는 로직에 대한 PR에서 자세히 말씀드리겠습니다.

2022-10-11 04:46 UTC, bigfanoftim approved these changes

2022-10-11 04:46 UTC, merged